### ISSUE TITLE
Проверка запроса на повышения прав UAC

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#1]
Необходимо добавить проверку на запрос прав администратора, если дирректория с программой находится в защищенной директории, то настройки не сохраняются, программа  #крашится

**Comment by krislechy** [comment]
Исправлено в релизе 0.110

**Comment by AzumiShinji** [comment]
Программа все еще завершает работу если находится в папке требующей повшыение прав и открыта не от имени администратора. Возникает, как минимум, при попытке сохранения настроек и открытии инвентаря

**Comment by krislechy** [comment]
> Программа все еще завершает работу если находится в папке требующей повшыение прав и открыта не от имени администратора. Возникает, как минимум, при попытке сохранения настроек и открытии инвентаря

Пришли видео у меня не повторяется эта ошибка

**Comment by AzumiShinji** [comment]
![1](https://user-images.githubusercontent.com/20335986/116131303-e4fd1180-a6d4-11eb-98b1-2ce24d7f1975.gif)

**Comment by AzumiShinji** [comment]
И еще пара. При попытке сохранить настройки, и обратиться к инвентарю - закрывается, запрос админских прав не происходит
![2](https://user-images.githubusercontent.com/20335986/116131640-4e7d2000-a6d5-11eb-9f7f-70de597b53d2.gif)
![3](https://user-images.githubusercontent.com/20335986/116131647-5046e380-a6d5-11eb-8527-6ffc6c8bee8c.gif)

**Comment by krislechy** [comment]
В тесте в v.0.150a
