### ISSUE TITLE
Некорректное поведение программы в трее

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#11]
Диалоговое окно в трее не закрывается при потере фокуса из-за чего может возникать его перекрытие панелью задач, а также при выходе программа не удалятся из трея и остается пока не наведешь на неё курсор, на гифке это второе действие после нажатия программа подвисает не на долго не закрывая также диалоговое окно, затем окно пропадает, а иконка - нет.
![2](https://user-images.githubusercontent.com/20335986/115763428-1f9d3c00-a3ad-11eb-9d77-591765a51bde.gif)

**Comment by krislechy** [comment]
Исправлено v.0.150a
