### ISSUE TITLE
Категории товаров

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#12]
При добавлении расходов категория по ключевым словам в наименовании товара не подтягивается
Не смотря на наличии следующих ключевых слов⬇
![image](https://user-images.githubusercontent.com/20335986/115766395-9851c780-a3b0-11eb-8f41-cb6a458ba74a.png)
Автоматически категория не встала
![image](https://user-images.githubusercontent.com/20335986/115766349-8a9c4200-a3b0-11eb-88bc-8e6aa102ddce.png)
![image](https://user-images.githubusercontent.com/20335986/115766377-91c35000-a3b0-11eb-81ea-2053b56e5ccb.png)

**Comment by krislechy** [comment]
Исправлено в v.0.150a, для редактирования категории необходимо выбирать пункт не для просто просмотра товаров, после выбора категории необходимо сохранить через меню в области товаров через правую кнопку мыши.
