### ISSUE TITLE
Иконка "Покупка рассчитана"

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#13]
Необходимо добавить большую зону для иконки _"Покупка рассчитана"_
![3](https://user-images.githubusercontent.com/20335986/115769779-968a0300-a3b4-11eb-9fcb-a365325fe352.gif)
Зона для hover, на текущий момент находится на самом глифе, который очень маленький, из-за чего сложно получить всплывающую подсказку. Как вариант закинуть глиф в контейнер при наведении на который триггерился бы hover

**Comment by krislechy** [comment]
Исправлено в v.0.150a
