### ISSUE TITLE
Отображение статистики

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#15]
Отображение оси с месяцами сейчас выглядит, как минимум некрасиво, из-за разной длины строки промежутки разные.
![image](https://user-images.githubusercontent.com/20335986/115772460-d0103d80-a3b7-11eb-907b-2853f983bbf1.png)
Решением может быть использование краткого формата даты который использует три символа, пример Янв, Фев / Jan, Feb....

**Comment by krislechy** [comment]
Исправлено в v.0.150a
