### ISSUE TITLE
Добавить действия на Enter

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#17]
В расходах необходимо при открытии окна новой покупки ставить фокус на поле _"Наименование покупки"_ и добавить сочетание Ctrl+Enter для завершения добавления покупки
![image](https://user-images.githubusercontent.com/20335986/115774640-81b06e00-a3ba-11eb-8b44-d683be662d40.png)

Также добавить добавление на Enter в категориях
![image](https://user-images.githubusercontent.com/20335986/115774900-d653e900-a3ba-11eb-8870-86328ebe6c24.png)

**Comment by krislechy** [comment]
Исправлено в v.0.150a
