### ISSUE TITLE
Возможность добавления нескольких тегов / ключевых слов за раз

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#18]
Добавить возможность занесения ключевых слов через запятую для множественного добавления разом, чтобы результатом добавления строки указанной на скрине был верхний вариант, а не нижний
![image](https://user-images.githubusercontent.com/20335986/115775073-11561c80-a3bb-11eb-8c5e-c2c14d621fa8.png)

**Comment by krislechy** [comment]
Исправлено в v.0.150a
