### ISSUE TITLE
Добавить пункт удалить

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#19]
Добавить пункт _"Удалить"_ в контекстное меню, а также на клавишу Delete, удаление должно сопровождаться подтверждающим DialogBox-ом
![image](https://user-images.githubusercontent.com/20335986/115775960-3ac37800-a3bc-11eb-998d-e55a42b461d7.png)

**Comment by krislechy** [comment]
Исправлено в v.0.150a
