### ISSUE TITLE
Не обновляются поля

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#2]
Сумма дохода в подзаголовке не обновляется после редактирования
![image](https://user-images.githubusercontent.com/20335986/115283944-bcb16800-a154-11eb-9f41-8cc3aace3a2f.png)

**Comment by AzumiShinji** [comment]
Также в расходах не обновляется поле "Рассчитанных покупок", до того момента пока не поменяешь просматриваемый месяц
![3](https://user-images.githubusercontent.com/20335986/115288949-ba520c80-a15a-11eb-90ae-1e4190946b1e.gif)

**Comment by krislechy** [comment]
> Сумма дохода в подзаголовке не обновляется после редактирования
> ![image](https://user-images.githubusercontent.com/20335986/115283944-bcb16800-a154-11eb-9f41-8cc3aace3a2f.png)

В работе

**Comment by krislechy** [comment]
Исправлено в релизе v.0.110
