### ISSUE TITLE
После добавления товара пропадает возможность изменения даты

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#20]
После добавления товара пропадает возможность изменения даты и наименования, вот только если наименование визуально отображает что оно недоступно, то вот дата нет.
![4](https://user-images.githubusercontent.com/20335986/115781810-91808000-a3c3-11eb-905b-958275ec6add.gif)

**Comment by krislechy** [comment]
Исправлено в v.0.150a
