### ISSUE TITLE
Не сохраняются расходы с копейками

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#21]
Расходы с копейками не сохраняются, программа не учитывает точку и запятую.
![5](https://user-images.githubusercontent.com/20335986/115782201-1075b880-a3c4-11eb-9ed4-4dc8eec25343.gif)

В телеграме та же проблема
![image](https://user-images.githubusercontent.com/20335986/115782268-24b9b580-a3c4-11eb-90ee-6a96be77a07c.png)

**Comment by krislechy** [comment]
Исправлено в v.0.150a
