### ISSUE TITLE
Обновление статистики

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#22]
После изменения суммы расхода появляется уведомление о том что необходимо сделать перерасчет, который происходит неизвестно как, и галочка на покупке о том что покупка учтена остается, статистика же не обновляется. Проверки из настроек не помогли.
Обновления должны происходить "под капотом" без вмешательства пользователя

**Comment by krislechy** [comment]
Исправлено в v.0.150a
