### ISSUE TITLE
Слишком большие кнопки

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#23]
![image](https://user-images.githubusercontent.com/20335986/116604234-846d0f00-a936-11eb-89cf-dea95938ae1a.png)
Как мне кажется стрелки занимают слишком много места, когда можно было уменьшив их даже поместить подписи к кнопкам перехода и возврата на дату

**Comment by AzumiShinji** [comment]
Можно сделать вариант компакт и полный, зависимое от размера окна

**Comment by krislechy** [comment]
Какие предложения? Я не понимаю мне нужен пример варианта как видишь ты.

**Comment by krislechy** [comment]
> Можно сделать вариант компакт и полный, зависимое от размера окна

Какие предложения? Я не понимаю мне нужен пример варианта как видишь ты.

**Comment by AzumiShinji** [comment]
![Без имени-1](https://user-images.githubusercontent.com/20335986/116680222-17985a00-a9b4-11eb-90d6-1560f2aa8b0d.png)
Как-то так мб

**Comment by krislechy** [comment]
выглядит не очень братан

**Comment by krislechy** [comment]
- [ ] 1

- [ ] 2

- [ ] 3

**Comment by AzumiShinji** [comment]
> выглядит не очень братан
> 
> > ![Без имени-1](https://user-images.githubusercontent.com/20335986/116680222-17985a00-a9b4-11eb-90d6-1560f2aa8b0d.png)
> > Как-то так мб

Ну так это примерно

![image](https://user-images.githubusercontent.com/20335986/116924871-1770b680-ac61-11eb-8792-77d11c8dd022.png)
Потому что при полноэкранном это тоже так себе

**Comment by krislechy** [comment]
Можно использовать разные варианты, но пустое место все равно будет.  На мой взгляд эта компановка элементов сейчас выглядит вполне сбалансировано (компактность/лаконичность).
