### ISSUE TITLE
Действие на Enter

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#26]
![image](https://user-images.githubusercontent.com/20335986/116924586-bc3ec400-ac60-11eb-8372-40b0ee3b30b3.png)
- [x] Добавить действие на Enter в расходах, при нажатии заканчивается редактирование, что равняется нажатию на кнопку с галочкой

![image](https://user-images.githubusercontent.com/20335986/116925195-8c43f080-ac61-11eb-96e7-527e9f2086a4.png)
- [x] Добавить действие на Enter в доходах

![image](https://user-images.githubusercontent.com/20335986/116925436-dc22b780-ac61-11eb-90f5-8bc57243317c.png)
- [x] В добавлении позиций товаров

**Comment by krislechy** [comment]
Исправлено в v.0.170a
