### ISSUE TITLE
Категории не учитываются в статистике

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#28]
Не смотря на то что все товары были забиты в категории, в статистике все как не определено
![image](https://user-images.githubusercontent.com/20335986/116926864-949d2b00-ac63-11eb-9b06-7508becaf01f.png)

**Comment by krislechy** [comment]
Исправлено в v.0.170a, Категории будут сохраняться автоматически если количество пользователей равно 1.
