### ISSUE TITLE
Несколько предложений для расходов и товаров

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#31]
- [x] Открывать товары двойным щелчком по покупке (Кстати покупку можно переименовать в транзакцию, так вроде более разделенно получится)
- [x] Добавить редактирование выделенной позиции товара на F2 и/или двойным щелчком (может редким двойным щелчком, как это работает в проводнике)
![image](https://user-images.githubusercontent.com/20335986/117215757-5b052500-ae07-11eb-9c4b-b3f644f2bc97.png)

- [x] В полях товара либо заменить "пустышки" плэйсхолдерами, либо сделать выделение всей строки при активации поля. Второй вариант более гибкий. Что я имею в виду, когда начинаешь редактировать новую позицию товара там есть стандартные значения, которые необходимо выделять и удалять, что добавляет лишние действия
Как это работает сейчас:
![3](https://user-images.githubusercontent.com/20335986/117216675-bf74b400-ae08-11eb-9333-40c83a763ac1.gif)

- [x] Не согласование порядка графы "Кол-во" и "Цена" в добавлении товара в новой покупке и редактировании уже готовой, необходимо сделать в обоих случаях один порядок
![image](https://user-images.githubusercontent.com/20335986/117216844-0fec1180-ae09-11eb-97e0-4201832ed625.png)
![image](https://user-images.githubusercontent.com/20335986/117216883-1c706a00-ae09-11eb-8b01-42a259796d4d.png)

- [x] Добавить автозаполнение товара при пустых полях, при транзакциях не включающих в себя разбивку на товары, если не введены количество и наименование - то наименование товара равняется наименованию покупки, а кол-во = 1
![image](https://user-images.githubusercontent.com/20335986/117223733-f94cb700-ae16-11eb-8e33-e5680e6e69d3.png)

**Comment by krislechy** [comment]
Последний пункт не понял совсем.

**Comment by krislechy** [comment]
Исправлено в v 0.200a
