### ISSUE TITLE
Отправка сообщений при выключенной программе

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#32]
Сообщения отправленные при выключенной программе зачитываются тем днем в который ты запустил прогу, можно ли получать дату отправки в бот чтобы засчитывать их в тот же день?
![image](https://user-images.githubusercontent.com/20335986/117221149-5f364000-ae11-11eb-95e1-ca0732fadbec.png)

**Comment by krislechy** [comment]
Исправлено в v 0.200a
