### ISSUE TITLE
Статистика по категориям

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#33]
Просьба вывести в легенде полную сумму трат не сокращая до К
![image](https://user-images.githubusercontent.com/20335986/117226488-6f541c80-ae1d-11eb-9755-a77be0a94210.png)

**Comment by krislechy** [comment]
В таком случае цифры могут наложиться друг на друга, что происходит у меня.
Могу предложить сделать чекбокс.

**Comment by krislechy** [comment]
Исправлено в v 0.200a
