### ISSUE TITLE
Неправильный расчет дохода

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#36]
По какой-то причине не учитывается копейка в расчете
![image](https://user-images.githubusercontent.com/20335986/117763927-50e28c80-b234-11eb-9230-777509495f6f.png)

**Comment by krislechy** [comment]
Исправлено в v.0.210a

**Comment by AzumiShinji** [comment]
Не исправлено
![1](https://user-images.githubusercontent.com/20335986/118425873-c639db80-b6d2-11eb-91c3-006cfe12bf55.gif)

**Comment by krislechy** [comment]
исправлено
