### ISSUE TITLE
Раскрывающийся список закрывается после редактирования

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#4]
Раскрывающийся список в расходах сампроизвольно закрывается после редактирования даты через DatePicker
![1](https://user-images.githubusercontent.com/20335986/115287632-2df31a00-a159-11eb-8505-68504cd4fbd9.gif)

**Comment by krislechy** [comment]
Потому что меняется дата, группировка списка основывается именно на дате, если покупка рассчитана то список закрывается по умолчанию (по условию), поэтому при смене даты меняется и дата группировки, а именно формируется уже новый список с элементами за эту дату. Соответственно при следующей проверке он закрывает список поскольку он рассчитан. Не является критичным, к тому же рассчитанные покупки не редактируются согласно штатной работе программы.

**Comment by AzumiShinji** [comment]
просьба исправить данное поведение

**Comment by krislechy** [comment]
Исправлено в v.0.121
