### ISSUE TITLE
Неправильный расчет среднего дохода за год

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#42]
Среднее арифметическое считается как сумма значений делённое на их количество, т.е. если какие-то месяцы не заполнены, или пользование программой началось не с начала года, то расчет среднего заработка неверен.
![image](https://user-images.githubusercontent.com/20335986/134260561-e2e68648-2d60-4146-a3b3-46237e587ab4.png)
Например в данном случае среднее должно равняться 2435,98. 
Необходима проверка если доход за месяц равен нулю и учитывать только не нулевые месяца.

**Comment by krislechy** [comment]
Исправлено
