### ISSUE TITLE
Непредвиденное закрытие программы из-за новых категорий

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#43]
При создании новой категории ей не присваивается иконка
![image](https://user-images.githubusercontent.com/20335986/134435478-9f575045-4f5b-423a-bee5-8fef9dbd1b3d.png)
И если оставить категорию как есть после создания, и добавить расход по этой категории, перейдя в статистику программа крашится

**Comment by krislechy** [comment]
Исправлено в v.0.261.0
