### ISSUE TITLE
Добавление автокатегорий без ручного вмешательства

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#44]
Смысл автокатегорий уменьшается, оттого что для их заполнения необходимо переходить в каждую транзакцию, покупку.
Было бы неплохо добавить настройку или улучшение чтобы категория проставлялась на момент добавления покупки, из того же телеграма. 
Также хотелось бы чтобы категории отображались на карточке покупки (пример на скрине) чтобы можно было сразу видеть где не заполнены категории
![Untitled-1](https://user-images.githubusercontent.com/20335986/134436333-713a5406-5ad2-4d1c-b8e2-e4b9148328f3.png)

**Comment by krislechy** [comment]
Исправлено в v.0.262.0
