### ISSUE TITLE
Баг с удалением позиций покупок

### ISSUE THREAD

**Issue by AzumiShinji** [krislechy/Castar_Release#45]
Если удалить позицию из покупки через контекстное меню, а не редактирование позиции, то статистика не обновляется и считается как с удаленными позициями.

Текст логов при том баге:
`--------------------29.09.2021 19:48:42--------------------`
`\/\/\/\/\/\/\/\/\/\/`
`Номер покупки в базе: 1174`
`Дата и время покупки: 29.09.2021 19:48:04`
`Наименование покупки: ООО ТЕСТ`
`Сумма покупки: 295,00 ₽`
`Кто оплатил: Артём (ID:337260896)`
`Текст: Сумма всех долей пользователей не равна сумме самой покупки: 751,00 ₽ != 295,00 ₽`
`\/\/\/\/\/\/\/\/\/\/`
`Номер покупки в базе: 1174`
`Дата и время покупки: 29.09.2021 19:48:04`
`Наименование покупки: ООО ТЕСТ`
`Сумма покупки: 295,00 ₽`
`Кто оплатил: Артём (ID:337260896)`
`Текст: Сумма долей покупки пользователя "Артём (ID: 337260896)" не равна сумме товаров: 751,00 ₽ != 295,00 ₽`

**Comment by krislechy** [comment]
Исправлено в 0.261.0a
